# fly.toml app configuration file generated for ics-back on 2024-06-18T13:33:20-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ics-back'
primary_region = 'ord'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/mnt/volume_mount/media'
  url_prefix = '/media/'

[[mounts]]
  source = 'database_volume'
  destination = '/mnt/volume_mount'
