# Generated by Django 5.0.6 on 2024-06-21 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_back_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('make', models.TextField(max_length=255)),
                ('model', models.TextField(max_length=255)),
                ('color', models.TextField(max_length=255)),
                ('notes', models.TextField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_warehouse_sections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='ics_back_app.warehousesection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_warehouse_sub_sections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseSubSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sub_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sub_sections', to='ics_back_app.warehousesubsection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_warehouse_sub_sub_sections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inventory_details', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_back_app.inventoryitems')),
                ('sub_sub_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_details', to='ics_back_app.warehousesubsubsection')),
            ],
        ),
    ]
