# Generated by Django 5.0.6 on 2024-06-13 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_back_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('make', models.TextField(max_length=255)),
                ('model', models.TextField(max_length=255)),
                ('color', models.TextField(max_length=255)),
                ('notes', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_back_app.warehousesection')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseSubSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sub_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_back_app.warehousesubsection')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_back_app.inventoryitems')),
                ('subsub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_back_app.warehousesubsubsection')),
            ],
        ),
    ]
