# Generated by Django 5.0.6 on 2024-06-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics_back_app', '0002_alter_profile_user_inventoryitems_warehousesection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_staff',
        ),
    ]
