# Generated by Django 5.0.6 on 2024-06-17 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_back_app', '0002_inventoryitems_warehousesection_warehousesubsection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydetails',
            name='sub_sub_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_details', to='ics_back_app.warehousesubsubsection'),
        ),
        migrations.AlterField(
            model_name='warehousesubsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='ics_back_app.warehousesection'),
        ),
        migrations.AlterField(
            model_name='warehousesubsubsection',
            name='sub_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sub_sections', to='ics_back_app.warehousesubsection'),
        ),
    ]
